### ISSUE TITLE
boolean型にfalse の値が入らない

### ISSUE THREAD

**Issue by chisato5582** [chisato5582/FoodFit#46]
Rails７系、esbuild , yarn, Tailwin, mysqlを使用しています。

４択のクイズアプリの制作を行なっています。そこで管理者画面でクイズの制作をしたいのですが、エラーが出て詰まってしまっています。
クイズ内容と、選択肢は別テーブルで管理しているのですが、
 Formオブジェクトを使い、同時に保存を行うようにしたいです。

以下エラー画面と、ログです

[![Image from Gyazo](https://i.gyazo.com/1f1e0de52a2a2427ee50c5136904743b.png)](https://gyazo.com/1f1e0de52a2a2427ee50c5136904743b)

```

Started POST "/admin/questions" for ::1 at 2023-08-24 16:43:02 +0900
Processing by Admin::QuestionsController#create as TURBO_STREAM
  Parameters: {"authenticity_token"=>"[FILTERED]", "question_create_form"=>{"content"=>"三大栄養素の糖質・脂質・たんぱく質は体の中でどんな働きをしている？", "reason"=>"生きるのに必要なエネルギーの源だよ！", "choices"=>{"choice1"=>"体の調子を整える", "choice2"=>"体の調子を整える", "choice3"=>"体の調子を整える", "correct3"=>"true", "choice4"=>"体の調子を整える"}}, "commit"=>"登録"}
  User Load (1.2ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 2 LIMIT 1
  TRANSACTION (0.1ms)  BEGIN
  ↳ app/forms/question_create_form.rb:20:in `save_with_choices'
  Question Create (0.3ms)  INSERT INTO `questions` (`content`, `reason`, `created_at`, `updated_at`) VALUES ('三大栄養素の糖質・脂質・たんぱく質は体の中でどんな働きをしている？', '生きるのに必要なエネルギーの源だよ！', '2023-08-24 07:43:02.449743', '2023-08-24 07:43:02.449743')
  ↳ app/forms/question_create_form.rb:20:in `save_with_choices'
  TRANSACTION (0.7ms)  COMMIT
  ↳ app/forms/question_create_form.rb:20:in `save_with_choices'
  TRANSACTION (0.1ms)  BEGIN
  ↳ app/forms/question_create_form.rb:22:in `save_with_choices'
  Question Load (0.2ms)  SELECT `questions`.* FROM `questions` WHERE `questions`.`id` = 34 LIMIT 1
  ↳ app/forms/question_create_form.rb:22:in `save_with_choices'
  TRANSACTION (0.1ms)  ROLLBACK
  ↳ app/forms/question_create_form.rb:22:in `save_with_choices'
Completed 422 Unprocessable Entity in 34ms (ActiveRecord: 8.4ms | Allocations: 14126)


  
ActiveRecord::RecordInvalid (バリデーションに失敗しました: 正誤を入力してください):
  
app/forms/question_create_form.rb:22:in `save_with_choices'
app/controllers/admin/questions_controller.rb:10:in `create'
```

テーブル設計は以下のようになっています。
問題内容テーブル(Question)と、選択肢テーブル(Choice)で関連付けを行い、correctカラムに関してはboolean型を用いています。
[![Image from Gyazo](https://i.gyazo.com/7f85aa12edd479942b3650fc58dd9654.png)](https://gyazo.com/7f85aa12edd479942b3650fc58dd9654)

以下関連するファイルの内容を記載します

choiceモデル
```
class Choice < ApplicationRecord
    belongs_to :question
    
    validates  :choice, presence: true
    validates  :correct, presence: true
    validates :correct, inclusion: [true, false]
end
```
quetsion_create_form.rb(Formオブジェクト)
```
class QuestionCreateForm
    include ActiveModel::Model
    include ActiveModel::Attributes

    attr_accessor :content, :reason, :choice, :correct, :question_id
    attribute :content, :string
    attribute :reason, :string
    attribute :choices, :string
    attribute :question_id, :integer


    def save_with_choices(
        choice_choice1:, choice_correct1:,
        choice_choice2:, choice_correct2:,
        choice_choice3:, choice_correct3:,
        choice_choice4:, choice_correct4:
    )

        @question = Question.create(content: content, reason: reason)
        self.question_id = @question.id
        Choice.create!([
            { choice: choice_choice1, correct: choice_correct1 || false, question_id: @question.id },
            { choice: choice_choice2, correct: choice_correct2 || false, question_id: @question.id },
            { choice: choice_choice3, correct: choice_correct3 || false, question_id: @question.id },
            { choice: choice_choice4, correct: choice_correct4 || false, question_id: @question.id }
        ])

    end
```

questionsコントローラ
```
class Admin::QuestionsController < Admin::BaseController

    def new
        @question = QuestionCreateForm.new
    end

    def create
        @question = QuestionCreateForm.new(question_params)

        if @question.save_with_choices(
            choice_choice1: params.dig(:question_create_form, :choices, :choice1),
            choice_correct1: params.dig(:question_create_form, :choices, :correct1),
            choice_choice2: params.dig(:question_create_form, :choices, :choice2),
            choice_correct2: params.dig(:question_create_form, :choices, :correct2),
            choice_choice3: params.dig(:question_create_form, :choices, :choice3),
            choice_correct3: params.dig(:question_create_form, :choices, :correct3),
            choice_choice4: params.dig(:question_create_form, :choices, :choice4),
            choice_correct4: params.dig(:question_create_form, :choices, :correct4)
        )
            redirect_to admin_question_path(@question.question_id), success: "問題を作成しました"
        else
            flash.now[:danger] = "問題の作成に失敗しました"
            render :new
        end
    end

    def question_params
        params.require(:question_create_form).permit(:content, :reason, choices: [:choice1, :correct1, :choice2, :correct2, :choice3, :correct3, :choice4, :correct4])
    end

```

マイグレーションファイル
```
class ChangeDatatypeCorrectOfChoices < ActiveRecord::Migration[7.0]
  def change
    change_column :choices, :correct, :boolean, null: false, default: false
  end
end
```
shema.rb
```
ActiveRecord::Schema[7.0].define(version: 2023_08_17_145043) do
  create_table "choices", charset: "utf8mb4", collation: "utf8mb4_0900_ai_ci", force: :cascade do |t|
    t.string "choice", null: false
    t.boolean "correct", default: false, null: false
    t.bigint "question_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["question_id"], name: "index_choices_on_question_id"
  end
```

また、原因を調べるため、Railsコンソールでfalseの場合のデータが保存できるか試してみました。
```
irb(main):008:0> Choice.create(choice: "体の調子を整える", correct: false, question_id:
 29)
  TRANSACTION (0.3ms)  BEGIN
  Question Load (0.5ms)  SELECT `questions`.* FROM `questions` WHERE `questions`.`id` = 29 LIMIT 1
  TRANSACTION (0.2ms)  ROLLBACK
=> 
#<Choice:0x0000000109b7e3a0
 id: nil,
 choice: "体の調子を整える",
 correct: false,
 question_id: 29,
 created_at: nil,
 updated_at: nil>
ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
irb(main):009:0> Choice.create(choice: "体の調子を整える", correct: true, question_id: 
29)
  TRANSACTION (0.3ms)  BEGIN
  Question Load (0.3ms)  SELECT `questions`.* FROM `questions` WHERE `questions`.`id` = 29 LIMIT 1
  Choice Create (0.7ms)  INSERT INTO `choices` (`choice`, `correct`, `question_id`, `created_at`, `updated_at`) VALUES ('体の調子を整える', TRUE, 29, '2023-08-24 07:38:24.637109', '2023-08-24 07:38:24.637109')
  TRANSACTION (0.7ms)  COMMIT
=> 
#<Choice:0x0000000109c57588
 id: 13,
 choice: "体の調子を整える",
 correct: true,
 question_id: 29,
 created_at: Thu, 24 Aug 2023 07:38:24.637109000 UTC +00:00,
 updated_at: Thu, 24 Aug 2023 07:38:24.637109000 UTC +00:00>
```
すると、true の場合は保存ができ、false の場合は失敗することが分かりました。

また、以下はデバックを行なった結果です
(選択肢1は正解、選択肢２は不正解です）
```
[14, 23] in /Users/aoyamachisatoshi/workspace/runteq/ポートフォリオ/PF/FoodFit/app/forms/question_create_form.rb
   14:         choice_choice2:, choice_correct2:,
   15:         choice_choice3:, choice_correct3:,
   16:         choice_choice4:, choice_correct4:
   17:     )
   18:         byebug
=> 19:         @question = Question.create(content: content, reason: reason)
   20:         self.question_id = @question.id
   21:         Choice.create!([
   22:             { choice: choice_choice1, correct: choice_correct1 || false, question_id: @question.id },
   23:             { choice: choice_choice2, correct: choice_correct2 || false, question_id: @question.id },
(byebug) choice_choice1
"正解"
(byebug) choice_choice2
"不正解"
(byebug) choice_choice1
"正解"
(byebug) choice_correct1
"true"
(byebug) choice_choice2
"不正解"
(byebug) choice_correct2
nil

```
false の値もうまく受け取れていないようでした。

最後に以下入力view の必要部分を抜粋で載せます
```
  <%= form_with model: @question, url: admin_questions_path, local: true do |f| %>
            <div class = 'form-group py-2'>
                <%= f.label :content, class: "text-font-color text-3xl" %>
                <%= f.text_area :content,  class: "form-control mb-3 py-2 px-10 mt-3 text-2xl" %>
            </div>
            <div class = 'form-group py-2'>
                <%= f.label :reason, class: "text-font-color text-3xl" %>
                <%= f.text_area :reason,  class: "form-control mb-3 py-2 px-10 mt-3 text-2xl" %>
            </div>

            <div class="grid grid-cols-1 divide-y divide-black-200 divide-y-4">
                <%= f.fields_for :choices do |choices_form| %>
                    <div>
                        <%= choices_form.label :choice1, class: "text-font-color text-3xl" %>
                        <%= choices_form.text_field :choice1,  class: "form-control mb-3 py-2 px-10 mt-3 text-2xl" %>
                        <div class='form-group py-2'>
                            <%= choices_form.label :correct1, class: "text-font-color text-3xl" %>
                            <%= choices_form.check_box :correct1, { checked: @question.correct }, true, false %>
                        </div>
                    </div>
                <% end %>
```

boolean型は、デフォルトでfalse が入るように設定しています。
また、Formオブジェクトでも<code>choice_correct1 || false</code>などを使い、nilが入らないようにしてみたのですが解決しませんでした。
何が原因でfalseが保存されないか、アドバイスをお願いします。

**Comment by kenchasonakai** [comment]
これですかね？
https://qiita.com/diskshima/items/9c0b6286d68c0c13bb68
